// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvQnMRIbXk0S2BIkOcAk0G2j4dipEibjQ',
    appId: '1:943859087430:web:cecb95384041d9636a7247',
    messagingSenderId: '943859087430',
    projectId: 'flutter-voluntaria-limeira-app',
    authDomain: 'flutter-voluntaria-limeira-app.firebaseapp.com',
    storageBucket: 'flutter-voluntaria-limeira-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-Zkihow1MXgp5RLuRWN7l3tvBLQbtKks',
    appId: '1:943859087430:android:7a712509ebd005cd6a7247',
    messagingSenderId: '943859087430',
    projectId: 'flutter-voluntaria-limeira-app',
    storageBucket: 'flutter-voluntaria-limeira-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsjZcDMIbTVn8y8aDhBZqiGpe1QlBCGtM',
    appId: '1:943859087430:ios:a936c53a9d71a1426a7247',
    messagingSenderId: '943859087430',
    projectId: 'flutter-voluntaria-limeira-app',
    storageBucket: 'flutter-voluntaria-limeira-app.firebasestorage.app',
    iosBundleId: 'com.example.projetoFinalParteMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsjZcDMIbTVn8y8aDhBZqiGpe1QlBCGtM',
    appId: '1:943859087430:ios:a936c53a9d71a1426a7247',
    messagingSenderId: '943859087430',
    projectId: 'flutter-voluntaria-limeira-app',
    storageBucket: 'flutter-voluntaria-limeira-app.firebasestorage.app',
    iosBundleId: 'com.example.projetoFinalParteMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvQnMRIbXk0S2BIkOcAk0G2j4dipEibjQ',
    appId: '1:943859087430:web:853d3c1dd4558ff46a7247',
    messagingSenderId: '943859087430',
    projectId: 'flutter-voluntaria-limeira-app',
    authDomain: 'flutter-voluntaria-limeira-app.firebaseapp.com',
    storageBucket: 'flutter-voluntaria-limeira-app.firebasestorage.app',
  );
}
